name: spotifyapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg:
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.0.11
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  image_picker: ^0.8.4+8
  get_it: ^7.1.1
  dartz: ^0.10.1
  cloud_firestore: ^5.1.0
  just_audio: 0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
  - family: Satoshi
    fonts:
      - asset: assets/fonts/Satoshi-Black.ttf
        weight: 900
      - asset: assets/fonts/Satoshi-Bold.ttf
        weight: 600
      - asset: assets/fonts/Satoshi-Medium.ttf
        weight: 500
      - asset: assets/fonts/Satoshi-Regular.ttf
        weight: 400
      - asset: assets/fonts/Satoshi-Light.ttf
        weight: 300


