// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDfOnIl3jGKK7RVoWP9MQGnO307-2zjE',
    appId: '1:400445420740:web:090469209994dcf47cc591',
    messagingSenderId: '400445420740',
    projectId: 'spotifyapp01',
    authDomain: 'spotifyapp01.firebaseapp.com',
    storageBucket: 'spotifyapp01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzRkUoBFgWEjQS3NkEgPFd6Ol0Q3sSPE',
    appId: '1:400445420740:android:4367b256d4e31d367cc591',
    messagingSenderId: '400445420740',
    projectId: 'spotifyapp01',
    storageBucket: 'spotifyapp01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5eeTa_YK9dDfqhMTsWzXpMS7c7hZqxtM',
    appId: '1:400445420740:ios:fe381eec5a1efd747cc591',
    messagingSenderId: '400445420740',
    projectId: 'spotifyapp01',
    storageBucket: 'spotifyapp01.appspot.com',
    iosBundleId: 'com.example.spotifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5eeTa_YK9dDfqhMTsWzXpMS7c7hZqxtM',
    appId: '1:400445420740:ios:fe381eec5a1efd747cc591',
    messagingSenderId: '400445420740',
    projectId: 'spotifyapp01',
    storageBucket: 'spotifyapp01.appspot.com',
    iosBundleId: 'com.example.spotifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVDfOnIl3jGKK7RVoWP9MQGnO307-2zjE',
    appId: '1:400445420740:web:4afd0e36507f7d137cc591',
    messagingSenderId: '400445420740',
    projectId: 'spotifyapp01',
    authDomain: 'spotifyapp01.firebaseapp.com',
    storageBucket: 'spotifyapp01.appspot.com',
  );
}
